### ISSUE TITLE
implement different types of LyricsProviders

### ISSUE THREAD

**Issue by pschichtel** [pschichtel/LyricsReloaded#2]
Currently the plugin only supports static access of websites, but many websites require to search for the songs as the URLs contain IDs.
Also there are websites that provide public APIs where we don''t need complicated and error prune content processing.

implementation ideas:

``` java
public interface LyricsProviderFactory<T extends LyricsProvider>
{
    T newLyricsProvider(YamlMappingNode configuration);
}
```

``` yaml
name: 'xy-lyrics.com'
type: 'static'
config:
    url: 'blabla'
    pattern: '<div>(?<lyrics>.*?)</div>'
    filters:
    - filter_a
    - filter_b
```

``` yaml
name: 'xy-lyrics-search.com'
type: 'search'
config:
    search-url: 'blabla'
    url-pattern: '<a href="(?<url>.*?)">{artist}-{name}'
    filters:
    - filter_a
    - filter_b
```

``` yaml
name: 'api.xy-lyrics.com'
type: 'api'
config:
    url: 'http://api.lyrics.tld/v3/lyrics/{artist}/{title}'
    data-path: 'lyrics.text'
```
